POST http://127.0.0.1:8888/api/register
Content-Type: application/application/json

{
    "name" : "Jonny 1",
    "email" : "Jonny1@gmail.com",
    "role" : 1,
    "password" : "password"
}

### create job

POST http://127.0.0.1:8888/api/createjob
Content-Type: application/application/json

{
    "position" : "IT Support",
    "description" : "IT Support for company",
    "salary" : "500000"
}

### create company
POST http://127.0.0.1:8888/api/createcompany
Content-Type: application/application/json

{
    "name" : "DPR Company"
}


### LOGIN

POST http://127.0.0.1:8888/api/login
Content-Type: application/application/json

{
    "email" : "Jonnyjiki@gmail.com",
    "password" : "password"
}

### Change Job
PUT http://127.0.0.1:8888/api/user/changejob/2
Content-Type: application/application/json

{
    "job_id" : 3
}

### Change Company
PUT http://127.0.0.1:8888/api/user/changecompany/4
Content-Type: application/application/json

{
    "company_id" : 1
}

### Delete user
DELETE http://127.0.0.1:8888/api/user/6

### update user
PUT http://127.0.0.1:8888/api/user/4
Content-Type: application/application/json

{
    "name" : "Jonny john KAMERUN",
    "email" : "jjjjj@gmail.com"
}

### parameter jobs
GET http://127.0.0.1:8888/api/employeebyjobs?id=2
### parameter companies
GET http://127.0.0.1:8888/api/employeebycompanies?id=3

### GET 1 USER
GET http://127.0.0.1:8888/api/user/2

### GET ALL USER
GET http://127.0.0.1:8888/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55X2lkIjoyLCJlbWFpbCI6Ikpvbm55amlraUBnbWFpbC5jb20iLCJleHAiOjE3MDMwMDQ1MzQsImlkIjoyLCJqb2JfaWQiOjQsIm5hbWUiOiJKb25ueSBqaWtpIiwicm9sZSI6Mn0.QZCpvyJz9xLgF9W2orilYmMA0VfPE4pxC8GGG7RwIJw

### GET ALL COMPANYs
GET http://127.0.0.1:8888/api/companies

### GET ALL JOB
GET http://127.0.0.1:8888/api/jobs

### GET company
